/**
 * Phase 17 — what the master Overview tab makes of every other tab's rows.
 *
 * The bug this pins down: the master tab was built at the same moment as the
 * Uber tab, reported the same freshness in its header, and showed none of
 * Uber's rides. Normalization was generated by the LLM next to
 * MasterDashboard.tsx, so it froze at the schemas known the day the master tab
 * was last built; Uber's `trip_datetime` ("Mar 16, 2026 1:23 pm") matched none
 * of that parser's date-fns formats, every ride normalized to `date: null`,
 * and the overview silently dropped the app from every dated view while the
 * header — which reports the newest `generatedAt` in the payload — truthfully
 * showed Uber's fresh timestamp.
 *
 * The parser now lives in the template as a shell file, so these tests run
 * against the exact module every generated app receives on its next deploy.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  findAmountColumn,
  findDateColumn,
  displayApp,
  normalizeDashboards,
  parseAmount,
  parseDate,
  periodKey,
  periodLabel,
  summarizeApps,
  type DashboardPayload,
} from '../../templates/dashboard/src/utils/masterOverview.js';
import { TemplateService, isShellOwnedGeneratedPath } from '../../src/services/template/TemplateService.js';
import { MASTER_DASHBOARD_PROMPT } from '../../src/config/dashboardPrompts.js';
import { SYSTEM_PROMPT } from '../../src/services/llm/prompts/systemPrompt.js';

/** Local-time parts, so assertions do not depend on the runner's timezone. */
function parts(date: Date | null) {
  expect(date).not.toBeNull();
  const value = date as Date;
  return {
    year: value.getFullYear(),
    month: value.getMonth(),
    day: value.getDate(),
    hours: value.getHours(),
    minutes: value.getMinutes(),
  };
}

describe('parseDate', () => {
  it('parses the Uber trip format that used to be dropped', () => {
    expect(parts(parseDate('Mar 16, 2026 1:23 pm'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 13, minutes: 23,
    });
  });

  it('parses the Uber payment timestamp (two-digit year, month first)', () => {
    // "16" cannot be a month, so this is unambiguously M/D/YY.
    expect(parts(parseDate('3/16/26 1:50 pm'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 13, minutes: 50,
    });
  });

  it('parses the Rapido ordinal format', () => {
    expect(parts(parseDate('Jun 10th 2026, 12:51 PM'))).toEqual({
      year: 2026, month: 5, day: 10, hours: 12, minutes: 51,
    });
  });

  it('keeps the instant of a zoned ISO timestamp', () => {
    const value = '2026-03-20T10:22:31+00:00';
    expect(parseDate(value)?.getTime()).toBe(Date.parse(value));
  });

  it('parses further shapes invoice emails use', () => {
    expect(parts(parseDate('2026-03-16 13:23:00'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 13, minutes: 23,
    });
    expect(parts(parseDate('16 Mar 2026, 9:05 am'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 9, minutes: 5,
    });
    expect(parts(parseDate('March 16, 2026'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 0, minutes: 0,
    });
    expect(parts(parseDate('16.03.2026'))).toEqual({
      year: 2026, month: 2, day: 16, hours: 0, minutes: 0,
    });
  });

  it('reads an ambiguous all-numeric date day-first, as before', () => {
    // Both parts could be a month; these are Indian invoices, so 10/06 is
    // 10 June, not 6 October. Documented, not accidental.
    expect(parts(parseDate('10/06/2026'))).toEqual({
      year: 2026, month: 5, day: 10, hours: 0, minutes: 0,
    });
  });

  it('accepts Date instances and epoch numbers', () => {
    const date = new Date(2026, 2, 16, 13, 23);
    expect(parseDate(date)).toBe(date);
    expect(parseDate(1_774_000_000_000)?.getTime()).toBe(1_774_000_000_000);
    expect(parseDate(1_774_000_000)?.getTime()).toBe(1_774_000_000_000);
  });

  it('returns null instead of throwing on unusable values', () => {
    for (const value of ['', '   ', 'not a date', 'Feb 30, 2026', null, undefined, {}, NaN]) {
      expect(parseDate(value)).toBeNull();
    }
  });
});

describe('parseAmount', () => {
  it('reads the shapes invoice rows carry', () => {
    expect(parseAmount(173.41)).toBe(173.41);
    expect(parseAmount('₹1,234.50')).toBe(1234.5);
    expect(parseAmount('Rs. 1,20,000')).toBe(120000);
    expect(parseAmount('(1,234.50)')).toBe(-1234.5);
  });

  it('returns null for cells with no amount in them', () => {
    for (const value of ['', '   ', '-', 'N/A', null, undefined, {}, Number.NaN]) {
      expect(parseAmount(value)).toBeNull();
    }
  });
});

/** The four dashboards in a real workspace, one row each. */
const UBER_ROW = {
  source_sender: 'uber_rides',
  email_date: '2026-03-16T08:21:03+00:00',
  trip_datetime: 'Mar 16, 2026 1:23 pm',
  suggested_fare: 168.41,
  total_paid: 173.41,
  payment_time: '3/16/26 1:50 pm',
  currency: 'INR',
};

const WORKSPACE: Record<string, DashboardPayload> = {
  amazon: {
    generatedAt: '2026-08-22T13:23:50.828Z',
    rows: [{ email_date: '2026-03-20T10:22:31+00:00', item_price: 640, order_total: 654 }],
  },
  rapido: {
    generatedAt: '2026-08-22T13:25:45.086Z',
    rows: [{
      email_date: '2026-06-14T20:13:32+00:00',
      ride_datetime: 'Jun 10th 2026, 12:51 PM',
      selected_price: 116,
      total_paid: 116,
    }],
  },
  'uber-rides': { generatedAt: '2026-08-22T13:32:22.794Z', rows: [UBER_ROW] },
};

describe('normalizeDashboards', () => {
  it('does not crash when protected payload keys are not strings', () => {
    expect(displayApp(null)).toBe('Dashboard');
    expect(displayApp(42)).toBe('42');
    expect(displayApp('urban_company')).toBe('Urban Company');
  });

  it('dates every Uber row instead of dropping the app', () => {
    const uber = normalizeDashboards(WORKSPACE).filter((record) => record.slug === 'uber-rides');
    expect(uber).toHaveLength(1);
    expect(uber[0].amount).toBe(173.41);
    expect(uber[0].countOnly).toBe(false);
    expect(parts(uber[0].date)).toEqual({ year: 2026, month: 2, day: 16, hours: 13, minutes: 23 });
    expect(uber[0].app).toBe('Uber Rides');
  });

  it('leaves no dashboard undated — the property the overview depends on', () => {
    const records = normalizeDashboards(WORKSPACE);
    for (const slug of Object.keys(WORKSPACE)) {
      const dated = records.filter((record) => record.slug === slug && record.date);
      expect(dated.length, `${slug} contributed no dated records`).toBeGreaterThan(0);
    }
  });

  it('falls back to a column that parses when the best-named one does not', () => {
    // A biller that starts emitting an unreadable trip_datetime must not
    // disappear from the overview: the next-best dated column takes over, and
    // when those are gone too, the email envelope date is still right there.
    const unreadableTrip = normalizeDashboards({
      'uber-rides': { rows: [{ ...UBER_ROW, trip_datetime: 'sometime last Tuesday' }] },
    });
    expect(parts(unreadableTrip[0].date)).toEqual({
      year: 2026, month: 2, day: 16, hours: 13, minutes: 50, // payment_time
    });

    const envelopeOnly = normalizeDashboards({
      'uber-rides': { rows: [{ ...UBER_ROW, trip_datetime: 'sometime last Tuesday', payment_time: '' }] },
    });
    expect(envelopeOnly[0].date?.getTime()).toBe(Date.parse(UBER_ROW.email_date));
  });

  it('dates a row whose primary column is blank from the next one', () => {
    // Real shape: 16 of 86 Uber rides carry an empty trip_datetime and nothing
    // but the envelope date. Choosing one column per dashboard drops them.
    const records = normalizeDashboards({
      'uber-rides': {
        rows: [UBER_ROW, { source_sender: 'uber_rides', trip_datetime: '', email_date: '2026-05-21T14:24:53+00:00' }],
      },
    });
    expect(records.filter((record) => record.date)).toHaveLength(2);
    expect(records[1].date?.getTime()).toBe(Date.parse('2026-05-21T14:24:53+00:00'));
    expect(records[1].countOnly).toBe(true);
  });

  it('marks rows with no usable amount as count-only', () => {
    const records = normalizeDashboards({ gym: { rows: [{ visited_on: '2026-03-16', class: 'HIIT' }] } });
    expect(records[0].amount).toBeNull();
    expect(records[0].countOnly).toBe(true);
    expect(records[0].date).not.toBeNull();
  });

  it('survives empty, missing and malformed payloads', () => {
    expect(normalizeDashboards(undefined)).toEqual([]);
    expect(normalizeDashboards({})).toEqual([]);
    expect(normalizeDashboards({ a: {}, b: { rows: [] } })).toEqual([]);
    expect(normalizeDashboards({ a: { rows: [{}] } })).toHaveLength(1);
  });
});

describe('column detection', () => {
  it('prefers the trip/ride column over the email envelope date', () => {
    expect(findDateColumn([UBER_ROW])).toBe('trip_datetime');
    expect(findAmountColumn([UBER_ROW])).toBe('total_paid');
  });

  it('reports nothing when a dashboard has no usable column', () => {
    const rows = [{ note: 'hello', tag: 'x' }];
    expect(findDateColumn(rows)).toBeUndefined();
    expect(findAmountColumn(rows)).toBeUndefined();
  });
});

describe('summarizeApps', () => {
  const records = normalizeDashboards(WORKSPACE);
  const summaries = summarizeApps(WORKSPACE, records);

  it('gives Uber a real last activity and spend', () => {
    const uber = summaries.find((summary) => summary.slug === 'uber-rides')!;
    expect(uber.transactions).toBe(1);
    expect(uber.datedTransactions).toBe(1);
    expect(uber.totalSpend).toBe(173.41);
    expect(uber.hasAmount).toBe(true);
    expect(parts(uber.lastActivity)).toEqual({ year: 2026, month: 2, day: 16, hours: 13, minutes: 23 });
  });

  it('covers every registered dashboard, in payload order', () => {
    expect(summaries.map((summary) => summary.slug)).toEqual(Object.keys(WORKSPACE));
  });
});

describe('period bucketing', () => {
  const date = new Date(2026, 2, 16, 13, 23); // Monday 16 March 2026

  it('buckets by week (Monday), month and quarter', () => {
    expect(periodKey(date, 'weekly')).toBe('2026-03-16');
    expect(periodKey(new Date(2026, 2, 22), 'weekly')).toBe('2026-03-16'); // Sunday
    expect(periodKey(date, 'monthly')).toBe('2026-03-01');
    expect(periodKey(date, 'quarterly')).toBe('2026-01-01');
  });

  it('labels the buckets it produces', () => {
    expect(periodLabel(periodKey(date, 'weekly'), 'weekly')).toBe('Mar 16');
    expect(periodLabel(periodKey(date, 'monthly'), 'monthly')).toBe('Mar 26');
    expect(periodLabel(periodKey(date, 'quarterly'), 'quarterly')).toBe('Q1 26');
    expect(periodLabel('nonsense', 'monthly')).toBe('nonsense');
  });
});

describe('shell ownership of the normalizer', () => {
  let projectDir: string;

  beforeEach(() => {
    projectDir = mkdtempSync(join(tmpdir(), 'openboard-master-'));
  });

  afterEach(() => {
    rmSync(projectDir, { recursive: true, force: true });
  });

  it('replaces a stale generated normalizer on the next deploy', async () => {
    const target = join(projectDir, 'src', 'utils', 'masterOverview.ts');
    mkdirSync(join(projectDir, 'src', 'utils'), { recursive: true });
    writeFileSync(target, 'export const stale = true\n', 'utf-8');

    const synced = await new TemplateService().syncShellFiles(projectDir);
    expect(synced).toContain('src/utils/masterOverview.ts');
    expect(readFileSync(target, 'utf-8')).toContain('export function normalizeDashboards');
  });

  it('rejects an LLM attempt to own the normalizer again', () => {
    expect(isShellOwnedGeneratedPath('utils/masterOverview.ts')).toBe(true);
    expect(isShellOwnedGeneratedPath('hooks/useAllDashboardsData.ts')).toBe(true);
    expect(isShellOwnedGeneratedPath('components/UberRidesDashboard.tsx')).toBe(false);
    expect(isShellOwnedGeneratedPath('utils/uberFares.ts')).toBe(false);
  });

  it('tells the model where normalization comes from', () => {
    expect(MASTER_DASHBOARD_PROMPT).toContain('utils/masterOverview');
    expect(MASTER_DASHBOARD_PROMPT).toContain('normalizeDashboards');
    expect(SYSTEM_PROMPT).toContain('src/utils/masterOverview.ts');
  });
});
