/**
 * masterOverview — how the master "Overview" tab reads every other tab's rows.
 *
 * Shell utility: synced from the template on every deploy, like the data hooks.
 * It used to be generated by the LLM alongside MasterDashboard.tsx, which made
 * it a snapshot of the schemas that existed the day the master tab was last
 * built. The master tab is only regenerated when the dashboard *set* changes,
 * so a biller that later shipped a date format the generated parser had never
 * seen was silently dropped: Uber's `trip_datetime` ("Mar 16, 2026 1:23 pm")
 * matched none of the parser's formats, so every ride normalised to
 * `date: null` and disappeared from the trend chart, the past-7-day and
 * this-month KPIs, and "last activity" — while the header, which reports the
 * newest `generatedAt` in the payload, correctly showed the fresh Uber
 * timestamp. The overview looked freshly built and was not showing the data it
 * had just been built from.
 *
 * Parsing every tab's rows is a cross-cutting correctness concern, not a
 * design choice, so the product owns it: one parser, tested in the CLI repo,
 * refreshed into every project on every deploy. MasterDashboard.tsx keeps the
 * presentation and imports from here.
 *
 * Deliberately dependency-free. date-fns lives in the generated app, not in
 * the CLI, and its `parse` rejects a string with any character the format did
 * not consume — which is how "MMM d, yyyy" came to reject
 * "Mar 16, 2026 1:23 pm". Plain arithmetic is both testable upstream and more
 * forgiving of the shapes invoice emails actually contain.
 */

export type Period = 'weekly' | 'monthly' | 'quarterly';

export interface DashboardPayload {
  rows?: Record<string, unknown>[];
  headers?: string[];
  summary?: string;
  generatedAt?: string;
}

export interface NormalizedRecord {
  /** Display label, e.g. "Uber Rides". */
  app: string;
  /** Dashboard slug the row came from, e.g. "uber-rides". */
  slug: string;
  date: Date | null;
  amount: number | null;
  /** No usable amount on this row — it counts as activity, not spend. */
  countOnly: boolean;
}

export interface AppSummary {
  app: string;
  slug: string;
  totalSpend: number;
  transactions: number;
  datedTransactions: number;
  lastActivity: Date | null;
  hasAmount: boolean;
}

/**
 * Preferred column names, best first. A dashboard with none of them falls back
 * to the loose matcher below.
 */
const AMOUNT_PRIORITY = [
  'total_paid',
  'final_paid',
  'paid_amount',
  'amount_paid',
  'grand_total',
  'order_total',
  'total_amount',
  'total',
  'net_amount',
  'net',
  'fare',
  'bill',
  'charge',
  'price',
  'amount',
  'paid',
];

const DATE_PRIORITY = [
  'ride_datetime',
  'trip_datetime',
  'booking_datetime',
  'ordered_at',
  'order_date',
  'paid_at',
  'payment_time',
  'invoice_date',
  'created_at',
  'date',
  'datetime',
  'email_date',
  'time',
];

const AMOUNT_PATTERN = /amount|paid|total|net|fare|bill|price|charge/;
const DATE_PATTERN = /date|time|ordered|paid|created|booked/;

const MONTHS: Record<string, number> = {
  jan: 0, january: 0,
  feb: 1, february: 1,
  mar: 2, march: 2,
  apr: 3, april: 3,
  may: 4,
  jun: 5, june: 5,
  jul: 6, july: 6,
  aug: 7, august: 7,
  sep: 8, sept: 8, september: 8,
  oct: 9, october: 9,
  nov: 10, november: 10,
  dec: 11, december: 11,
};

const MONTH_LABELS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
];

function normalizedKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

export function displayApp(slug: unknown): string {
  const value = typeof slug === 'string' ? slug : String(slug ?? '');
  return value
    .split(/[-_\s]/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(' ') || 'Dashboard';
}

// ---------------------------------------------------------------------------
// Value parsing
// ---------------------------------------------------------------------------

/** Amount from a cell: strips currency symbols, thousands separators, spaces. */
export function parseAmount(value: unknown): number | null {
  if (typeof value === 'number') return Number.isFinite(value) ? value : null;
  if (typeof value !== 'string') return null;

  const text = value.trim();
  if (!text) return null;

  // Pull the number out rather than deleting everything around it: stripping
  // non-digits turned "Rs. 1,20,000" into ".120000" — 0.12 — because the dot
  // in "Rs." survived, and lakh grouping is exactly what these invoices use.
  const match = /-?\d[\d,]*(?:\.\d+)?/.exec(text.replace(/\s/g, ''));
  if (!match) return null;

  const parsed = Number(match[0].replace(/,/g, ''));
  if (!Number.isFinite(parsed)) return null;

  // "(1,234.50)" is a negative in accounting exports.
  return /^\(.*\)$/.test(text) ? -Math.abs(parsed) : parsed;
}

const MIDNIGHT = { hours: 0, minutes: 0, seconds: 0 };

function buildDate(
  year: number,
  month: number,
  day: number,
  time: { hours: number; minutes: number; seconds: number },
): Date | null {
  if (month < 0 || month > 11 || day < 1 || day > 31) return null;
  const date = new Date(year, month, day, time.hours, time.minutes, time.seconds, 0);
  if (Number.isNaN(date.getTime())) return null;
  // Rejects the impossible ("Feb 30"), which JS would silently roll forward.
  if (date.getFullYear() !== year || date.getMonth() !== month || date.getDate() !== day) {
    return null;
  }
  return date;
}

/** Clock time anywhere in `text`; midnight when the value carries none. */
function extractTime(text: string): { hours: number; minutes: number; seconds: number } {
  const match = /(\d{1,2}):(\d{2})(?::(\d{2}))?\s*([ap])\.?\s?m\.?/i.exec(text)
    ?? /(\d{1,2}):(\d{2})(?::(\d{2}))?/.exec(text);
  if (!match) return MIDNIGHT;

  let hours = Number(match[1]);
  const minutes = Number(match[2]);
  const seconds = Number(match[3] ?? 0);
  const meridiem = match[4]?.toLowerCase();

  if (meridiem === 'p' && hours < 12) hours += 12;
  if (meridiem === 'a' && hours === 12) hours = 0;
  if (hours > 23 || minutes > 59 || seconds > 59) return MIDNIGHT;

  return { hours, minutes, seconds };
}

/** "26" → 2026, "84" → 1984. Two-digit years appear in payment timestamps. */
function expandYear(raw: string): number {
  const year = Number(raw);
  if (raw.length > 2) return year;
  return year < 70 ? 2000 + year : 1900 + year;
}

/**
 * Date from a cell, across the formats invoice emails actually use.
 *
 * Ambiguous all-numeric dates (both parts <= 12, e.g. "10/06/2026") are read
 * day-first: these dashboards are built from Indian invoices, and day-first is
 * what the previous parser assumed. "3/16/26" is unambiguous — 16 cannot be a
 * month — and reads month-first.
 */
export function parseDate(value: unknown): Date | null {
  if (value instanceof Date) return Number.isNaN(value.getTime()) ? null : value;

  if (typeof value === 'number' && Number.isFinite(value)) {
    // Epoch seconds vs milliseconds: anything below ~1e11 as milliseconds is
    // 1973 or earlier, which no invoice is.
    const ms = Math.abs(value) < 1e11 ? value * 1000 : value;
    const epoch = new Date(ms);
    return Number.isNaN(epoch.getTime()) ? null : epoch;
  }

  if (typeof value !== 'string') return null;
  const text = value.trim();
  if (!text) return null;

  // ISO with a zone ("2026-03-20T10:22:31+00:00") — the instant is explicit.
  if (/^\d{4}-\d{2}-\d{2}T/.test(text)) {
    const iso = new Date(text);
    if (!Number.isNaN(iso.getTime())) return iso;
  }

  // Strip ordinals ("Jun 10th 2026") and collapse whitespace.
  const cleaned = text
    .replace(/(\d{1,2})(st|nd|rd|th)\b/gi, '$1')
    .replace(/\s+/g, ' ')
    .trim();

  // ISO-ish date, optionally followed by a clock: "2026-03-16 13:23:00".
  const isoish = /^(\d{4})-(\d{1,2})-(\d{1,2})(?:[T ](.*))?$/.exec(cleaned);
  if (isoish) {
    const built = buildDate(
      Number(isoish[1]),
      Number(isoish[2]) - 1,
      Number(isoish[3]),
      isoish[4] ? extractTime(isoish[4]) : MIDNIGHT,
    );
    if (built) return built;
  }

  // Month name first: "Mar 16, 2026 1:23 pm", "Mar 16 2026", "March 16, 2026".
  const monthFirst = /^([A-Za-z]{3,9})\.?,? (\d{1,2}),? (\d{2,4})\b(.*)$/.exec(cleaned);
  const monthFirstIndex = monthFirst ? MONTHS[monthFirst[1].toLowerCase()] : undefined;
  if (monthFirst && monthFirstIndex !== undefined) {
    return buildDate(
      expandYear(monthFirst[3]),
      monthFirstIndex,
      Number(monthFirst[2]),
      extractTime(monthFirst[4] ?? ''),
    );
  }

  // Day first: "16 Mar 2026, 1:23 pm".
  const dayFirst = /^(\d{1,2}) ([A-Za-z]{3,9})\.?,? (\d{2,4})\b(.*)$/.exec(cleaned);
  const dayFirstIndex = dayFirst ? MONTHS[dayFirst[2].toLowerCase()] : undefined;
  if (dayFirst && dayFirstIndex !== undefined) {
    return buildDate(
      expandYear(dayFirst[3]),
      dayFirstIndex,
      Number(dayFirst[1]),
      extractTime(dayFirst[4] ?? ''),
    );
  }

  // All-numeric: "3/16/26 1:50 pm", "16-03-2026", "16.03.2026 13:23".
  const numeric = /^(\d{1,2})[/.-](\d{1,2})[/.-](\d{2,4})\b(.*)$/.exec(cleaned);
  if (numeric) {
    const first = Number(numeric[1]);
    const second = Number(numeric[2]);
    const year = expandYear(numeric[3]);
    const time = extractTime(numeric[4] ?? '');
    return second > 12 && first <= 12
      ? buildDate(year, first - 1, second, time)
      : buildDate(year, second - 1, first, time);
  }

  // Last resort: whatever the browser recognises. The individual dashboard
  // tabs parse with `new Date(value)`, so this keeps the overview from
  // dropping a row the tab it summarises is happy to show. Only shapes none of
  // the patterns above recognised reach here — a date those patterns read and
  // found impossible ("Feb 30, 2026") stays rejected rather than being rolled
  // forward into a day that never happened.
  const native = new Date(cleaned);
  return Number.isNaN(native.getTime()) ? null : native;
}

// ---------------------------------------------------------------------------
// Column detection
// ---------------------------------------------------------------------------

function columnCandidates(
  rows: Record<string, unknown>[],
  priority: string[],
  matcher: RegExp,
): string[] {
  const keys = [...new Set(rows.flatMap((row) => Object.keys(row ?? {})))];
  const ranked: string[] = [];

  for (const candidate of priority) {
    const key = keys.find((name) => normalizedKey(name) === candidate);
    if (key && !ranked.includes(key)) ranked.push(key);
  }
  for (const key of keys) {
    if (!ranked.includes(key) && matcher.test(normalizedKey(key))) ranked.push(key);
  }
  return ranked;
}

/**
 * Highest-priority column whose values actually parse.
 *
 * Ranking by name alone is what let one dashboard vanish from the overview: a
 * column named exactly like the best candidate wins the pick, and if its
 * values do not parse, every row is dropped even when a perfectly good
 * `email_date` sits beside it. Sampling the data decides it instead.
 */
function usableColumns<T>(
  rows: Record<string, unknown>[],
  candidates: string[],
  parse: (value: unknown) => T | null,
): string[] {
  const sample = rows.slice(0, 60);
  return candidates.filter((key) => sample.some((row) => parse(row?.[key]) !== null));
}

/**
 * Column of dates nobody named like one — "visited_on", "trip_start".
 *
 * Only consulted when no column matched by name, and deliberately strict:
 * strings only (a plain number would read as an epoch, so every quantity
 * column would look like a date) and most of the sampled values must parse.
 */
function sniffDateColumn(rows: Record<string, unknown>[]): string | undefined {
  const sample = rows.slice(0, 60);
  const keys = [...new Set(sample.flatMap((row) => Object.keys(row ?? {})))];

  for (const key of keys) {
    let seen = 0;
    let parsed = 0;
    for (const row of sample) {
      const value = row?.[key];
      if (typeof value !== 'string' || !value.trim()) continue;
      seen += 1;
      if (parseDate(value)) parsed += 1;
    }
    if (seen > 0 && parsed / seen >= 0.6) return key;
  }
  return undefined;
}

/** Column the overview reads dates from, or undefined when none parses. */
export function findDateColumn(rows: Record<string, unknown>[]): string | undefined {
  return findDateColumns(rows)[0];
}

/**
 * Every column the overview may read a date from, best first.
 *
 * A list rather than one pick, because rows within a dashboard are not
 * uniform: 16 of 86 Uber rides carry an empty `trip_datetime` and nothing but
 * the email envelope date, and a per-dashboard column choice drops exactly
 * those rows out of every dated view.
 */
export function findDateColumns(rows: Record<string, unknown>[]): string[] {
  const named = usableColumns(rows, columnCandidates(rows, DATE_PRIORITY, DATE_PATTERN), parseDate);
  if (named.length > 0) return named;
  const sniffed = sniffDateColumn(rows);
  return sniffed ? [sniffed] : [];
}

/**
 * Column the overview reads amounts from, or undefined when none parses.
 *
 * One column per dashboard, unlike dates: falling back per row would mix a
 * "suggested fare" into a total of "amount paid" and quietly change what the
 * spend figures mean. A row missing that column is count-only.
 */
export function findAmountColumn(rows: Record<string, unknown>[]): string | undefined {
  return usableColumns(rows, columnCandidates(rows, AMOUNT_PRIORITY, AMOUNT_PATTERN), parseAmount)[0];
}

/** First of the candidate columns that yields a date for this row. */
function rowDate(row: Record<string, unknown>, columns: string[]): Date | null {
  for (const key of columns) {
    const date = parseDate(row?.[key]);
    if (date) return date;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Aggregation
// ---------------------------------------------------------------------------

/** Every dashboard's rows flattened into one comparable shape. */
export function normalizeDashboards(
  dashboards: Record<string, DashboardPayload> | undefined,
): NormalizedRecord[] {
  return Object.entries(dashboards ?? {}).flatMap(([slug, payload]) => {
    const rows = Array.isArray(payload?.rows) ? payload.rows : [];
    if (rows.length === 0) return [];

    const app = displayApp(slug);
    const dateColumns = findDateColumns(rows);
    const amountColumn = findAmountColumn(rows);

    return rows.map((row) => {
      const amount = amountColumn ? parseAmount(row?.[amountColumn]) : null;
      return {
        app,
        slug,
        date: rowDate(row, dateColumns),
        amount,
        countOnly: amount === null,
      };
    });
  });
}

/** Per-app totals, keyed off the same normalized records the charts use. */
export function summarizeApps(
  dashboards: Record<string, DashboardPayload> | undefined,
  records: NormalizedRecord[],
): AppSummary[] {
  return Object.keys(dashboards ?? {}).map((slug) => {
    const app = displayApp(slug);
    const appRecords = records.filter(
      (record) => record.slug === slug || record.app === app,
    );
    const dated = appRecords.filter((record) => record.date);
    const lastActivity = dated.reduce<Date | null>(
      (latest, record) =>
        !latest || (record.date && record.date > latest) ? record.date : latest,
      null,
    );
    const amountRecords = appRecords.filter((record) => record.amount !== null);

    return {
      app,
      slug,
      totalSpend: amountRecords.reduce((sum, record) => sum + (record.amount ?? 0), 0),
      transactions: appRecords.length,
      datedTransactions: dated.length,
      lastActivity,
      hasAmount: amountRecords.length > 0,
    };
  });
}

// ---------------------------------------------------------------------------
// Period bucketing (the Weekly / Monthly / Quarterly toggle)
// ---------------------------------------------------------------------------

function isoDay(date: Date): string {
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${date.getFullYear()}-${month}-${day}`;
}

/** Stable bucket key for a record's date. Weeks start Monday. */
export function periodKey(date: Date, period: Period): string {
  if (period === 'weekly') {
    const start = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    start.setDate(start.getDate() - ((start.getDay() + 6) % 7));
    return isoDay(start);
  }
  if (period === 'quarterly') {
    return isoDay(new Date(date.getFullYear(), Math.floor(date.getMonth() / 3) * 3, 1));
  }
  return isoDay(new Date(date.getFullYear(), date.getMonth(), 1));
}

/** Axis label for a bucket key produced by periodKey. */
export function periodLabel(key: string, period: Period): string {
  const parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(key);
  if (!parts) return key;
  const year = Number(parts[1]);
  const month = Number(parts[2]) - 1;
  const day = Number(parts[3]);
  if (month < 0 || month > 11) return key;

  if (period === 'weekly') return `${MONTH_LABELS[month]} ${day}`;
  if (period === 'quarterly') {
    return `Q${Math.floor(month / 3) + 1} ${`${year}`.slice(-2)}`;
  }
  return `${MONTH_LABELS[month]} ${`${year}`.slice(-2)}`;
}
