export const DASHBOARD_LOADING_REMARKS = [
  'Asking the spreadsheet to stop pretending it is a database.',
  'Turning suspicious columns into confident-looking charts.',
  'Finding the insight your CSV has been hiding out of spite.',
  'Convincing numbers to wear business casual.',
  'Polishing KPIs until management can see their reflection.',
  'Teaching raw data the ancient art of looking intentional.',
  'Negotiating with null values. They are dramatic today.',
  'Making charts from chaos, because apparently that is a job now.',
  'Your dashboard is being assembled from ambition and delimiters.',
  'Persuading date columns to admit what century they belong to.',
  'Converting spreadsheet anxiety into executive confidence.',
  'Putting tiny suits on your metrics.',
  'Searching for trends that did not file a leave request.',
  'Rebranding messy data as exploratory analytics.',
  'Making the outliers feel seen, but not too seen.',
  'Summoning a chart that says "strategy" without laughing.',
  'Giving your CSV a promotion it may not deserve.',
  'Preparing a dashboard your stakeholders can overinterpret.',
  'Asking the data nicely before we ask it aggressively.',
  'Building visual truth, with light cosmetic surgery.',
  'Dusting off the columns that clearly gave up last quarter.',
  'Turning rows into revelations, or at least into rectangles.',
  'Adding just enough polish to make variance look intentional.',
  'Extracting insights before the data changes its story.',
  'Giving your metrics a stage and a mildly judgmental spotlight.',
  'Making business intelligence from business confusion.',
  'Sorting facts from spreadsheet folklore.',
  'Trying to make the y-axis emotionally stable.',
  'Making a dashboard while the data quietly judges us both.',
  'Convincing totals and averages to share custody of the truth.',
  'Finding patterns before the meeting finds excuses.',
  'Turning "just a CSV" into "please see slide 4".',
  'Letting the numbers speak, then editing for tone.',
  'Giving your data a haircut and a LinkedIn headline.',
  'Checking whether the trend is real or just dramatic lighting.',
  'Building the dashboard equivalent of a straight face.',
  'Persuading duplicate rows to confess.',
  'Charting the decline of certainty in high resolution.',
  'Arranging metrics so they look like they planned this.',
  'Letting the dashboard cook. The oven is mostly statistics.',
  'Squeezing insight out of cells that preferred privacy.',
  'Preparing visuals for humans with seven open tabs.',
  'Teaching the data to stop mumbling.',
  'Making a pie chart reconsider its life choices.',
  'Attempting to make "miscellaneous" look less like a confession.',
  'Running a small courtroom drama between columns.',
  'Giving your dataset the makeover it hinted at in Q2.',
  'Turning row counts into something your boss can point at.',
  'Finding the signal. The noise has hired lawyers.',
  'Building a dashboard before the scope changes again.',
  'Assembling insight from fragments and mild optimism.',
  'Translating data into shapes, because apparently words were too direct.',
  'Applying chart therapy to your metrics.',
  'Making the dashboard look calm so nobody suspects the data.',
  'Checking if the correlation is meaningful or just flirting.',
  'Convincing your columns to stand in a straight line.',
  'Waiting for the LLM to stop admiring its own prompt.',
  'Brewing a dashboard strong enough for Monday.',
  'Trying not to let the nulls win.',
  'Turning data fumes into dashboard fuel.',
  'Making the legend useful, a bold experiment.',
  'Giving the trendline a reason to get out of bed.',
  'Searching for insight in a place marked final_final_v3.',
  'Staging a tasteful intervention for your spreadsheet.',
  'Asking the model to be brilliant, concise, and somehow cheap.',
  'Compressing panic into a tidy grid layout.',
  'Helping your data cosplay as a product feature.',
  'Finding the story your rows are legally allowed to tell.',
  'Making charts that look more certain than anyone feels.',
  'Turning questionable inputs into presentable outputs.',
  'Preparing a dashboard for people who say "quick question".',
  'Giving your dataset a personality, against medical advice.',
  'Making insight soup. The croutons are filters.',
  'Polishing the axis labels so they stop looking abandoned.',
  'Checking whether "Other" is a category or a cry for help.',
  'Making a dashboard that can survive a screen share.',
  'Converting silent columns into loud opinions.',
  'Calculating whether the data or the deadline is more hostile.',
  'Letting the LLM stare into the dataset until it blinks.',
  'Building something credible from rows with trust issues.',
  'Making your CSV look like it has a roadmap.',
  'Assembling charts with the confidence of a consultant.',
  'Giving the metrics enough contrast to start an argument.',
  'Turning tabular fog into executive weather.',
  'Finding insight before someone asks for a donut chart.',
  'Making the dashboard emotionally available.',
  'Reassuring the data that dashboards happen to good files too.',
  'Preparing visual evidence for the court of stakeholder opinion.',
  'Adding structure to the place where structure went to retire.',
  'Turning fiscal dread into a respectable line chart.',
  'Making a bar chart that has seen things but remains professional.',
  'Checking if the data is clean or just wearing a blazer.',
  'Helping the model pretend this was obvious all along.',
  'Converting operational entropy into tasteful panels.',
  'Giving your filters a sense of purpose.',
  'Making sure the dashboard does not scream in production.',
  'Looking for anomalies without making eye contact.',
  'Turning "can you just" into several hundred tokens.',
  'Letting the charts rehearse before the big stakeholder meeting.',
  'Making your data less raw and more medium-rare.',
  'Preparing insights fresh from the mildly haunted data cellar.',
] as const;

